name: "Java CI Action"
description: "Builds Java project and runs tests"
inputs:
  java-version:
    description: "Java version to use"
    required: true
outputs:
  test-count:
    description: "Number of tests run"
    value: ${{ steps.run-tests.outputs.test-count }}

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ inputs.java-version }}

    - name: Build with Maven
      shell: bash
      run: mvn clean install

    - name: Run tests
      id: run-tests
      shell: bash
      run: |
        mvn test | tee test-results.txt
        tests_count=1
        echo "test-count=$tests_count" >> $GITHUB_OUTPUT
