name: "Call Reusable Java CI Workflow"

on:
  push:
    branches:
      - main

jobs:
  display-test-count:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Java CI Action
        uses: './.github/actions/java-ci-action'
        with:
          java-version: 17
        id: java-ci

