name: Dispatch inputs

on:
  workflow_dispatch:
    inputs:
      terraform_version:
        type: choice
        description: 'Terraform version'
        options:
          - 1.3.9
          - 1.5.7
      region:
        description: 'Region'
        type: choice
        options:
          - eu-central-1
          - cn-north-1
      command:
        description: 'Define action'
        type: choice
        options:
          - apply
          - destroy

run-name: 'Hello world, branch [${{ github.ref_name }}]'
env:
  TERRAFORM_VERSION: ${{ inputs.terraform_version }}
  REGION: ${{ inputs.region }}
  COMMAND: ${{ inputs.command }}

jobs:  
  first_job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Echo
        run: echo ${{ env.TERRAFORM_VERSION }} ${{ env.REGION }} ${{ env.COMMAND }}
