name: Docker Services

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

run-name: 'Docker services, branch [${{ github.ref_name }}]'

jobs:
  build_on_docker:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
      localstack:
        image: localstack/localstack:latest
        env:
          SERVICES: sqs
          DEFAULT_REGION: us-east-1
          EDGE_PORT: 4566
        ports:
          - 4566:4566
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven
      - name: Build with Maven
        run: mvn -B package
