name: Java strategy matrix

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

run-name: 'Java strategy matrix, branch [${{ github.ref_name }}]'

jobs:
  build_strategy_matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        java_version: [17, 21]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java_version }}
        distribution: 'corretto'
        cache: maven
    - name: Build with Maven
      run: mvn -B package
    - name: Upload JUnit Test Results
      uses: actions/upload-artifact@v4
      with:
        name: junit-test-results
        path: target/surefire-reports/*.txt
